- name: Copy RabbitMq repo File
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install RabbitMq Server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: Start RabbitMq Server
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Add Application User
  community.rabbitmq.rabbitmq_user:
    user: "{{ lookup('community.hashi_vault.hashi_vault', 'roboshop-{{env}}/data/rabbitmq:user token={{ vault_token }} url=http://vault-internal.sairamdevops.online:8200')}"
    password: {{ lookup('community.hashi_vault.hashi_vault', 'roboshop-{{env}}/data/rabbitmq:password token={{ vault_token }} url=http://vault-internal.sairamdevops.online:8200')}
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present