- name: Install MySql Server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Start MySql Service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Setup MySql Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ lookup('community.hashi_vault.hashi_vault', 'roboshop-{{env}}/data/mysql:mysql_root_password token={{ vault_token }} url=http://vault-internal.sairamdevops.online:8200')}



