- name: Copy the Service File
  ansible.builtin.template:
    src: "{{ component }}"
    dest: /etc/systemd/system/{{ component }}.service

- name: Start the Application Service
  ansible.buildin.systemd_service:
    name: "{{ component }}"
    state: restarted
    enabled: yes
    daemon_reload: yes