- name: Copy the Service File
  ansible.builtin.template:
    src: "{{ app_name }}"
    dest: /etc/systemd/system/{{ app_name }}.service

- name: Start the Application Service
  ansible.buildin.systemd_service:
    name: "{{ app_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes