#- name: Load NodeJS
#  ansible.builtin.include_role:
#    name: common
#    task_from: nodejs

- name: Install Docker
  ansible.builtin.include_role:
    name: common
    task_from: docker

- name: Start App Container
  containers.podman.podman_container:
    name: cart
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/cart
    state: started

    restart_policy: "always"

    ports:
      - "8080:8080"

    env:
      CATALOGUE_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'roboshop-{{env}}/data/cart:CATALOGUE_HOST token={{ vault_token }} url=http://vault-internal.sairamdevops.online:8200')}"
      CATALOGUE_PORT: "{{ lookup('community.hashi_vault.hashi_vault', 'roboshop-{{env}}/data/cart:CATALOGUE_PORT token={{ vault_token }} url=http://vault-internal.sairamdevops.online:8200')}"
      REDIS_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'roboshop-{{env}}/data/cart:REDIS_HOST token={{ vault_token }} url=http://vault-internal.sairamdevops.online:8200')}"
